version: '3.8'
services:
  app:
    build:
      context: .
      args:
        NODE_ENV: development
    container_name: my-new-project-dev
    command: npm run dev
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "8080:3000"
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    container_name: mongodb-dev
    ports:
      - "2717:27017"
    volumes:
      - db-data:/data/db

  test:
    build:
      context: .
      args:
        NODE_ENV: test
    container_name: my-new-project-test
    command: npm test
    env_file:
      - .env.test
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mongo

  seed:
    build:
      context: .
      args:
        NODE_ENV: development
    container_name: my-new-project-seed
    command: npm run seed
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mongo

volumes:
  db-data: