services:
  - type: web
    name: survey-analysis-backend
    env: docker
    region: oregon
    plan: starter
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: "80"
      - key: DB_CONNECTION_STRING
        sync: false # Indicates this variable will be set in Render dashboard
      - key: JWT_SECRET
        sync: false # Indicates this variable will be set in Render dashboard
    routes:
      - type: primary
        name: survey-analysis-backend
